mode : all

csv-file : 
env-path : ../.env

latency : 
  times : 10

settings : 
  times : 50

stt : 
  groq : 
    model-name : whisper-large-v3-turbo
    sample-rate : 16000 
    sample-width : 2 
    channels : 1

  google : 

    detect-langs : [hi-IN , mr-IN , pt-PT]
    # detect-langs : []
    sample-rate : 16000
    sample-width : 2 
    channels : 1
    model-name : chirp_3

  deepgram : 

    sample-rate : 16000 
    sample-width : 2 
    channels : 1

  assembly-ai : 