vector-db-url : 

manager-model : 
manager-provider : groq 

persona-model : moonshotai/kimi-k2-instruct-0905
persoan-provider : groq 

critical-slots : [Name , Course , Percentage , City]
optional-slots : [Preference , StreamSubjects , PassingYear]

manager-prompt-file : 
query-rephraser-prompt-file : assets/prompts/query_rephraser.md
persona-prompt-file : 

hangpup-responses-file : assets/jsons/hangup_responses.json

manager : 
  prompt : assets/prompts/manager.md
  model : llama-3.3-70b-versatile
  provider : groq 
  temperature : 0

persona : 
  prompt : assets/prompts/persona.md
  model : gpt-4.1-2025-04-14
  # model : gpt-5-nano-2025-08-07
  provider : openai
  temperature : 0

rephraser : 
  prompt : assets/prompts/query_rephraser.md
  model : llama-3.3-70b-versatile
  provider : groq
  temperature : 1


responses : assets/jsons/responses.json

vector-db : 
  url : http://localhost:9000/search